insert into cities (name, country_id) values ('Kaczory', 262);
insert into cities (name, country_id) values ('Huangshanguan', 936);
insert into cities (name, country_id) values ('Hà Đông', 377);
insert into cities (name, country_id) values ('Waiwukak', 515);
insert into cities (name, country_id) values ('Villeneuve-sur-Lot', 865);
insert into cities (name, country_id) values ('Milotice', 99);
insert into cities (name, country_id) values ('Daming', 473);
insert into cities (name, country_id) values ('Dushan', 616);
insert into cities (name, country_id) values ('Perm', 479);
insert into cities (name, country_id) values ('Colesberg', 577);
insert into cities (name, country_id) values ('Gabrovo', 661);
insert into cities (name, country_id) values ('Aliuroba', 348);
insert into cities (name, country_id) values ('Marihatag', 715);
insert into cities (name, country_id) values ('Shamboyacu', 372);
insert into cities (name, country_id) values ('Las Palmas', 516);
insert into cities (name, country_id) values ('Nogueira', 211);
insert into cities (name, country_id) values ('Dubki', 745);
insert into cities (name, country_id) values ('Saltsjö-Boo', 574);
insert into cities (name, country_id) values ('Huangge', 937);
insert into cities (name, country_id) values ('Huangnaihai', 204);
insert into cities (name, country_id) values ('Porto-Novo', 529);
insert into cities (name, country_id) values ('San Pedro', 400);
insert into cities (name, country_id) values ('Jixian', 79);
insert into cities (name, country_id) values ('Tempeh Tengah', 479);
insert into cities (name, country_id) values ('Guaíra', 501);
insert into cities (name, country_id) values ('Rifeng', 916);
insert into cities (name, country_id) values ('Houxixi', 425);
insert into cities (name, country_id) values ('Novyy Starodub', 610);
insert into cities (name, country_id) values ('Kittilä', 280);
insert into cities (name, country_id) values ('Vessada', 769);
insert into cities (name, country_id) values ('Amsterdam', 101);
insert into cities (name, country_id) values ('Danyang', 295);
insert into cities (name, country_id) values ('El Sauce', 643);
insert into cities (name, country_id) values ('Sanshengyuan', 48);
insert into cities (name, country_id) values ('Tiên Phước', 37);
insert into cities (name, country_id) values ('Lugait', 309);
insert into cities (name, country_id) values ('Mosrentgen', 78);
insert into cities (name, country_id) values ('Qalqīlyah', 617);
insert into cities (name, country_id) values ('Gisiliba', 753);
insert into cities (name, country_id) values ('Santa Cruz das Flores', 162);
insert into cities (name, country_id) values ('Puamata', 690);
insert into cities (name, country_id) values ('Sere', 897);
insert into cities (name, country_id) values ('Ad Dimnah', 62);
insert into cities (name, country_id) values ('Puerto Morazán', 982);
insert into cities (name, country_id) values ('Šabac', 993);
insert into cities (name, country_id) values ('Cikiruh Wetan', 221);
insert into cities (name, country_id) values ('T’ianet’i', 807);
insert into cities (name, country_id) values ('Charyshskoye', 155);
insert into cities (name, country_id) values ('Ramos', 907);
insert into cities (name, country_id) values ('Haoguantun', 796);
insert into cities (name, country_id) values ('Muskegon', 91);
insert into cities (name, country_id) values ('Baranoa', 183);
insert into cities (name, country_id) values ('Meilin', 330);
insert into cities (name, country_id) values ('Santa Cruz del Sur', 651);
insert into cities (name, country_id) values ('Ritchie', 519);
insert into cities (name, country_id) values ('Issy-les-Moulineaux', 193);
insert into cities (name, country_id) values ('Takahashi', 245);
insert into cities (name, country_id) values ('Wugui', 224);
insert into cities (name, country_id) values ('Tengqiao', 3);
insert into cities (name, country_id) values ('La Laguna', 397);
insert into cities (name, country_id) values ('Clarin', 639);
insert into cities (name, country_id) values ('Jianchang', 81);
insert into cities (name, country_id) values ('Tembisa', 371);
insert into cities (name, country_id) values ('Thành phố Bạc Liêu', 71);
insert into cities (name, country_id) values ('Irtyshskiy', 481);
insert into cities (name, country_id) values ('Saint Louis', 314);
insert into cities (name, country_id) values ('Senekal', 686);
insert into cities (name, country_id) values ('Yingchun', 466);
insert into cities (name, country_id) values ('Cabano', 875);
insert into cities (name, country_id) values ('Novoselitsa', 482);
insert into cities (name, country_id) values ('Sabaneta', 895);
insert into cities (name, country_id) values ('Licheng', 431);
insert into cities (name, country_id) values ('Mino', 510);
insert into cities (name, country_id) values ('Zvenyhorodka', 752);
insert into cities (name, country_id) values ('Astana', 329);
insert into cities (name, country_id) values ('Bila', 257);
insert into cities (name, country_id) values ('Kōfu-shi', 445);
insert into cities (name, country_id) values ('Liugong', 877);
insert into cities (name, country_id) values ('General San Martín', 241);
insert into cities (name, country_id) values ('Huangshi', 873);
insert into cities (name, country_id) values ('Plato', 268);
insert into cities (name, country_id) values ('Bang Ban', 749);
insert into cities (name, country_id) values ('Gnojnik', 612);
insert into cities (name, country_id) values ('Parigi', 160);
insert into cities (name, country_id) values ('Promyshlennaya', 384);
insert into cities (name, country_id) values ('Praga Północ', 629);
insert into cities (name, country_id) values ('Cosquín', 654);
insert into cities (name, country_id) values ('Beaufort', 319);
insert into cities (name, country_id) values ('Shazhenxi', 705);
insert into cities (name, country_id) values ('Žlutice', 506);
insert into cities (name, country_id) values ('Qīr Moāv', 710);
insert into cities (name, country_id) values ('Nakkila', 375);
insert into cities (name, country_id) values ('Kulpin', 524);
insert into cities (name, country_id) values ('Lujing Zhen', 572);
insert into cities (name, country_id) values ('Şaqānis', 37);
insert into cities (name, country_id) values ('Shuiquan', 820);
insert into cities (name, country_id) values ('Qingqu', 890);
insert into cities (name, country_id) values ('Cisasak', 49);
insert into cities (name, country_id) values ('Lárdos', 503);
insert into cities (name, country_id) values ('Borino', 370);
insert into cities (name, country_id) values ('Piedra Blanca', 502);
insert into cities (name, country_id) values ('Wysoka', 915);
insert into cities (name, country_id) values ('Kawahmanuk', 679);
insert into cities (name, country_id) values ('Malasin', 865);
insert into cities (name, country_id) values ('Dashiqiao', 154);
insert into cities (name, country_id) values ('Dearborn', 608);
insert into cities (name, country_id) values ('Ngantru', 594);
insert into cities (name, country_id) values ('Rohia', 158);
insert into cities (name, country_id) values ('Teresita', 875);
insert into cities (name, country_id) values ('Castres', 157);
insert into cities (name, country_id) values ('Blažovice', 183);
insert into cities (name, country_id) values ('Aksu', 37);
insert into cities (name, country_id) values ('Takai', 577);
insert into cities (name, country_id) values ('Tabia', 918);
insert into cities (name, country_id) values ('Katwijk', 424);
insert into cities (name, country_id) values ('Xitou', 332);
insert into cities (name, country_id) values ('Bandar-e Māhshahr', 100);
insert into cities (name, country_id) values ('Tanjungbahagia', 408);
insert into cities (name, country_id) values ('Zeleneč', 90);
insert into cities (name, country_id) values ('Vale de Figueira', 476);
insert into cities (name, country_id) values ('Tawangrejo', 697);
insert into cities (name, country_id) values ('Al Bīrah', 365);
insert into cities (name, country_id) values ('Rancabelut', 748);
insert into cities (name, country_id) values ('Mauraro', 669);
insert into cities (name, country_id) values ('Monteros', 74);
insert into cities (name, country_id) values ('Sukmoilang', 611);
insert into cities (name, country_id) values ('Yanhong', 126);
insert into cities (name, country_id) values ('Lloqan', 890);
insert into cities (name, country_id) values ('Luau', 62);
insert into cities (name, country_id) values ('Wajak', 224);
insert into cities (name, country_id) values ('Sindanghayu', 350);
insert into cities (name, country_id) values ('Dipayal', 286);
insert into cities (name, country_id) values ('Changuinola', 137);
insert into cities (name, country_id) values ('Quintães', 309);
insert into cities (name, country_id) values ('Avanca', 309);
insert into cities (name, country_id) values ('Petropavlovsk', 917);
insert into cities (name, country_id) values ('Cipaku', 168);
insert into cities (name, country_id) values ('Sindangsari', 146);
insert into cities (name, country_id) values ('Łaziska Górne', 501);
insert into cities (name, country_id) values ('Lago dos Rodrigues', 322);
insert into cities (name, country_id) values ('Matarraque', 718);
insert into cities (name, country_id) values ('Quintela', 962);
insert into cities (name, country_id) values ('Smiltene', 259);
insert into cities (name, country_id) values ('Potet', 693);
insert into cities (name, country_id) values ('Mintian', 513);
insert into cities (name, country_id) values ('Poroçan', 564);
insert into cities (name, country_id) values ('Prawdzinski', 77);
insert into cities (name, country_id) values ('Thaon-les-Vosges', 641);
insert into cities (name, country_id) values ('Yanda Bayo', 566);
insert into cities (name, country_id) values ('Xiangyang', 19);
insert into cities (name, country_id) values ('Michałów-Reginów', 485);
insert into cities (name, country_id) values ('Qibu', 637);
insert into cities (name, country_id) values ('Campana', 985);
insert into cities (name, country_id) values ('Codrington', 1);
insert into cities (name, country_id) values ('Drobin', 939);
insert into cities (name, country_id) values ('Mankono', 641);
insert into cities (name, country_id) values ('Longtian', 857);
insert into cities (name, country_id) values ('Harrison Brook', 122);
insert into cities (name, country_id) values ('Santa', 477);
insert into cities (name, country_id) values ('Norfolk', 404);
insert into cities (name, country_id) values ('Kakan', 46);
insert into cities (name, country_id) values ('Tonghae', 854);
insert into cities (name, country_id) values ('Baruta', 883);
insert into cities (name, country_id) values ('Dubna', 668);
insert into cities (name, country_id) values ('Metz', 618);
insert into cities (name, country_id) values ('Baratan', 921);
insert into cities (name, country_id) values ('Tuanjie', 142);
insert into cities (name, country_id) values ('Karanganyarkrajan', 594);
insert into cities (name, country_id) values ('Pitogo', 31);
insert into cities (name, country_id) values ('Beaung Tengah', 609);
insert into cities (name, country_id) values ('Sumberkemuning', 539);
insert into cities (name, country_id) values ('Wangcheng', 323);
insert into cities (name, country_id) values ('Laborie', 670);
insert into cities (name, country_id) values ('Manika', 136);
insert into cities (name, country_id) values ('Muldersdriseloop', 578);
insert into cities (name, country_id) values ('Ivouani', 920);
insert into cities (name, country_id) values ('Kure', 88);
insert into cities (name, country_id) values ('Zhangdian', 851);
insert into cities (name, country_id) values ('Rego de Água', 594);
insert into cities (name, country_id) values ('Inazawa', 66);
insert into cities (name, country_id) values ('Malekān', 442);
insert into cities (name, country_id) values ('Bagorejo', 111);
insert into cities (name, country_id) values ('Ordzhonikidzevskaya', 576);
insert into cities (name, country_id) values ('Shihuajian', 364);
insert into cities (name, country_id) values ('Xianghu', 400);
insert into cities (name, country_id) values ('Roodepoort', 468);
insert into cities (name, country_id) values ('Fria', 95);
insert into cities (name, country_id) values ('Espinal', 314);
insert into cities (name, country_id) values ('Крушопек', 847);
insert into cities (name, country_id) values ('Lawa-an', 272);
insert into cities (name, country_id) values ('Makuyuni', 294);
insert into cities (name, country_id) values ('Khlong Hat', 413);
insert into cities (name, country_id) values ('Dobrá', 978);
insert into cities (name, country_id) values ('Sindou', 990);
insert into cities (name, country_id) values ('Neuilly-sur-Seine', 704);
insert into cities (name, country_id) values ('La Gi', 672);
insert into cities (name, country_id) values ('Jiangkou', 795);
insert into cities (name, country_id) values ('Ubonratana', 216);
insert into cities (name, country_id) values ('Zaslawye', 915);
insert into cities (name, country_id) values ('Skene', 805);
insert into cities (name, country_id) values ('General Lavalle', 408);
insert into cities (name, country_id) values ('Além', 751);
insert into cities (name, country_id) values ('Mendi', 5);
insert into cities (name, country_id) values ('White River', 745);
insert into cities (name, country_id) values ('Martinópolis', 187);
insert into cities (name, country_id) values ('Banatsko Karađorđevo', 513);
insert into cities (name, country_id) values ('Denglong', 824);
insert into cities (name, country_id) values ('Belém', 484);
insert into cities (name, country_id) values ('Jishigang', 808);
insert into cities (name, country_id) values ('Komaki', 742);
insert into cities (name, country_id) values ('Kalchevaya', 827);
insert into cities (name, country_id) values ('Tawa', 878);
insert into cities (name, country_id) values ('Dadaha', 255);
insert into cities (name, country_id) values ('Borne Sulinowo', 334);
insert into cities (name, country_id) values ('Mauá', 685);
insert into cities (name, country_id) values ('Bielawy', 94);
insert into cities (name, country_id) values ('Goroka', 872);
insert into cities (name, country_id) values ('Zliv', 473);
insert into cities (name, country_id) values ('Sonorejo', 926);
insert into cities (name, country_id) values ('Härnösand', 30);
insert into cities (name, country_id) values ('Ilembula', 286);
insert into cities (name, country_id) values ('Feondari', 900);
insert into cities (name, country_id) values ('Ar Rudayyif', 13);
insert into cities (name, country_id) values ('Khromtau', 64);
insert into cities (name, country_id) values ('Nenotes', 402);
insert into cities (name, country_id) values ('Khenifra', 449);
insert into cities (name, country_id) values ('Anliang', 192);
insert into cities (name, country_id) values ('Headlands', 531);
insert into cities (name, country_id) values ('Shalazhi', 78);
insert into cities (name, country_id) values ('Qiqian', 81);
insert into cities (name, country_id) values ('Murygino', 62);
insert into cities (name, country_id) values ('Yaozhanzi', 325);
insert into cities (name, country_id) values ('Surat Thani', 703);
insert into cities (name, country_id) values ('Cikuning', 557);
insert into cities (name, country_id) values ('Karangkancana', 157);
insert into cities (name, country_id) values ('Linköping', 111);
insert into cities (name, country_id) values ('Wysoka', 545);
insert into cities (name, country_id) values ('Varkaus', 856);
insert into cities (name, country_id) values ('Jambean', 593);
insert into cities (name, country_id) values ('Perístasi', 252);
insert into cities (name, country_id) values ('Botou', 590);
insert into cities (name, country_id) values ('Dobrzeń Wielki', 17);
insert into cities (name, country_id) values ('Yinchuan', 51);
insert into cities (name, country_id) values ('Tongren', 442);
insert into cities (name, country_id) values ('Cunha', 847);
insert into cities (name, country_id) values ('Lukulu', 466);
insert into cities (name, country_id) values ('Pierzchnica', 372);
insert into cities (name, country_id) values ('Shengli', 112);
insert into cities (name, country_id) values ('Paris 07', 706);
insert into cities (name, country_id) values ('Aţ Ţaybah', 84);
insert into cities (name, country_id) values ('Velventós', 401);
insert into cities (name, country_id) values ('Grebnevo', 525);
insert into cities (name, country_id) values ('Vostryakovo', 637);
insert into cities (name, country_id) values ('Strängnäs', 123);
insert into cities (name, country_id) values ('Diamante', 406);
insert into cities (name, country_id) values ('Haocun', 992);
insert into cities (name, country_id) values ('Sangesi', 23);
insert into cities (name, country_id) values ('Longtian', 707);
insert into cities (name, country_id) values ('Sok Kwu Wan', 591);
insert into cities (name, country_id) values ('Tarbes', 115);
insert into cities (name, country_id) values ('Mishixiang', 847);
insert into cities (name, country_id) values ('Xuanbao', 969);
insert into cities (name, country_id) values ('Nangkaruka', 500);
insert into cities (name, country_id) values ('Oulmes', 386);
insert into cities (name, country_id) values ('Saint-Ouen', 534);
insert into cities (name, country_id) values ('Hacienda La Calera', 409);
insert into cities (name, country_id) values ('San Sebastián', 626);
insert into cities (name, country_id) values ('La Jutosa', 428);
insert into cities (name, country_id) values ('Xinshui', 482);
insert into cities (name, country_id) values ('Virden', 589);
insert into cities (name, country_id) values ('Lebyazh’ye', 915);
insert into cities (name, country_id) values ('Qeshm', 43);
insert into cities (name, country_id) values ('Luna', 329);
insert into cities (name, country_id) values ('Sosnówka', 544);
insert into cities (name, country_id) values ('Chemnitz', 301);
insert into cities (name, country_id) values ('Mỹ Thọ', 548);
insert into cities (name, country_id) values ('Ranot', 351);
insert into cities (name, country_id) values ('Kasui', 796);
insert into cities (name, country_id) values ('Al Qābil', 54);
insert into cities (name, country_id) values ('Újezd', 862);
insert into cities (name, country_id) values ('Padangcermin', 546);
insert into cities (name, country_id) values ('Gœsdorf', 890);
insert into cities (name, country_id) values ('Al Jahrā’', 1000);
insert into cities (name, country_id) values ('Bandaran', 414);
insert into cities (name, country_id) values ('Xiashe', 172);
insert into cities (name, country_id) values ('Sungairaya', 557);
insert into cities (name, country_id) values ('Żabno', 846);
insert into cities (name, country_id) values ('Rembes', 471);
insert into cities (name, country_id) values ('Dongpu', 134);
insert into cities (name, country_id) values ('Zhangjiachang', 310);
insert into cities (name, country_id) values ('Gushikawa', 287);
insert into cities (name, country_id) values ('Kajar', 522);
insert into cities (name, country_id) values ('Huangqiao', 360);
insert into cities (name, country_id) values ('Perštejn', 966);
insert into cities (name, country_id) values ('Tetandara', 488);
insert into cities (name, country_id) values ('Capayán', 878);
insert into cities (name, country_id) values ('Kabukarudi', 732);
insert into cities (name, country_id) values ('Madolenihm Municipality Government', 706);
insert into cities (name, country_id) values ('Yixing', 307);
insert into cities (name, country_id) values ('Неготино', 903);
insert into cities (name, country_id) values ('Calceta', 853);
insert into cities (name, country_id) values ('Melati', 119);
insert into cities (name, country_id) values ('Montluel', 247);
insert into cities (name, country_id) values ('Córdoba', 549);
insert into cities (name, country_id) values ('Sarvābād', 790);
insert into cities (name, country_id) values ('Belišće', 478);
insert into cities (name, country_id) values ('Ballinteer', 118);
insert into cities (name, country_id) values ('Shatoja', 23);
insert into cities (name, country_id) values ('Al Ibrāhīmīyah', 197);
insert into cities (name, country_id) values ('Skien', 686);
insert into cities (name, country_id) values ('Croix', 954);
insert into cities (name, country_id) values ('Point Hill', 350);
insert into cities (name, country_id) values ('Pertunmaa', 140);
insert into cities (name, country_id) values ('Belyy Gorodok', 827);
insert into cities (name, country_id) values ('Libušín', 722);
insert into cities (name, country_id) values ('Zengtian', 117);
insert into cities (name, country_id) values ('Ciorescu', 558);
insert into cities (name, country_id) values ('Lolotique', 666);
insert into cities (name, country_id) values ('Laolong', 199);
insert into cities (name, country_id) values ('Ciudad Nueva', 579);
insert into cities (name, country_id) values ('Vilar do Monte', 223);
insert into cities (name, country_id) values ('Labruge', 194);
insert into cities (name, country_id) values ('Hotonj', 832);
insert into cities (name, country_id) values ('Dongjingcheng', 505);
insert into cities (name, country_id) values ('Chifeng', 987);
insert into cities (name, country_id) values ('Shijiang', 235);
insert into cities (name, country_id) values ('Yingcui', 209);
insert into cities (name, country_id) values ('Gazojak', 10);
insert into cities (name, country_id) values ('Junaynat Raslān', 637);
insert into cities (name, country_id) values ('Zuogaimanma', 930);
insert into cities (name, country_id) values ('Hangbu', 289);
insert into cities (name, country_id) values ('Ciherang', 829);
insert into cities (name, country_id) values ('Ljukovo', 427);
insert into cities (name, country_id) values ('Nguigmi', 276);
insert into cities (name, country_id) values ('Magoúla', 458);
insert into cities (name, country_id) values ('Yangxiang', 299);
insert into cities (name, country_id) values ('Nishinoomote', 178);
insert into cities (name, country_id) values ('Guchang', 424);
insert into cities (name, country_id) values ('Şuraabad', 505);
insert into cities (name, country_id) values ('Purísima', 282);
insert into cities (name, country_id) values ('Yazman', 672);
insert into cities (name, country_id) values ('Sremski Karlovci', 420);
insert into cities (name, country_id) values ('Washington', 621);
insert into cities (name, country_id) values ('Florencio Sánchez', 141);
insert into cities (name, country_id) values ('Suicheng', 179);
insert into cities (name, country_id) values ('Xinkai', 501);
insert into cities (name, country_id) values ('Nong Ki', 559);
insert into cities (name, country_id) values ('Umanggudang', 814);
insert into cities (name, country_id) values ('Piripiri', 5);
insert into cities (name, country_id) values ('Gaojian', 752);
insert into cities (name, country_id) values ('Oepula', 895);
insert into cities (name, country_id) values ('Cachoeira do Sul', 910);
insert into cities (name, country_id) values ('Purwosari', 935);
insert into cities (name, country_id) values ('Changkeng', 139);
insert into cities (name, country_id) values ('Kafr Thulth', 169);
insert into cities (name, country_id) values ('Guri i Zi', 437);
insert into cities (name, country_id) values ('Gandara', 645);
insert into cities (name, country_id) values ('Kālīganj', 799);
insert into cities (name, country_id) values ('Piraí do Sul', 85);
insert into cities (name, country_id) values ('Chojata', 182);
insert into cities (name, country_id) values ('Nazrēt', 370);
insert into cities (name, country_id) values ('Kuvshinovo', 431);
insert into cities (name, country_id) values ('Seririt', 16);
insert into cities (name, country_id) values ('Brumadinho', 110);
insert into cities (name, country_id) values ('Kabale', 637);
insert into cities (name, country_id) values ('Gangkou', 789);
insert into cities (name, country_id) values ('Cascavel', 151);
insert into cities (name, country_id) values ('San Nicolas', 541);
insert into cities (name, country_id) values ('Heshang', 995);
insert into cities (name, country_id) values ('Ancasti', 664);
insert into cities (name, country_id) values ('Khursā', 512);
insert into cities (name, country_id) values ('Ngaoundéré', 204);
insert into cities (name, country_id) values ('Puerto Guzmán', 282);
insert into cities (name, country_id) values ('Shigony', 231);
insert into cities (name, country_id) values ('Waepau', 52);
insert into cities (name, country_id) values ('La Quebrada', 495);
insert into cities (name, country_id) values ('Sumberbakti', 388);
insert into cities (name, country_id) values ('Dingshu', 552);
insert into cities (name, country_id) values ('Phonsavan', 345);
insert into cities (name, country_id) values ('Tres Isletas', 908);
insert into cities (name, country_id) values ('Novosin’kovo', 855);
insert into cities (name, country_id) values ('Tabia', 271);
insert into cities (name, country_id) values ('Al Miftāḩ', 1000);
insert into cities (name, country_id) values ('Timurlorong', 891);
insert into cities (name, country_id) values ('Lanckorona', 758);
insert into cities (name, country_id) values ('Nagbukel', 143);
insert into cities (name, country_id) values ('Krajan Bakalan', 120);
insert into cities (name, country_id) values ('Ḩawsh ‘Īsá', 490);
insert into cities (name, country_id) values ('Iwase', 593);
insert into cities (name, country_id) values ('Chaoyang', 801);
insert into cities (name, country_id) values ('Mauloo', 748);
insert into cities (name, country_id) values ('Plavy', 874);
insert into cities (name, country_id) values ('Ibarra', 643);
insert into cities (name, country_id) values ('Gelap', 261);
insert into cities (name, country_id) values ('Yarang', 510);
insert into cities (name, country_id) values ('La Jagua de Ibirico', 936);
insert into cities (name, country_id) values ('Pergamos', 913);
insert into cities (name, country_id) values ('Perjuangan', 814);
insert into cities (name, country_id) values ('Rana', 926);
insert into cities (name, country_id) values ('Turka', 497);
insert into cities (name, country_id) values ('Vilarinho', 219);
insert into cities (name, country_id) values ('Västerås', 89);
insert into cities (name, country_id) values ('Osiedle-Nowiny', 791);
insert into cities (name, country_id) values ('Al ‘Āliyah', 257);
insert into cities (name, country_id) values ('Karlshamn', 904);
insert into cities (name, country_id) values ('Ariana', 268);
insert into cities (name, country_id) values ('Qiling', 596);
insert into cities (name, country_id) values ('Banjar Kawan', 863);
insert into cities (name, country_id) values ('Haarlem', 833);
insert into cities (name, country_id) values ('Gusang', 859);
insert into cities (name, country_id) values ('Fradelos', 16);
insert into cities (name, country_id) values ('Lianzhu', 73);
insert into cities (name, country_id) values ('Himaya', 391);
insert into cities (name, country_id) values ('Beaverton', 43);
insert into cities (name, country_id) values ('Sumurasin', 992);
insert into cities (name, country_id) values ('Karabanovo', 522);
insert into cities (name, country_id) values ('Amargosa', 741);
insert into cities (name, country_id) values ('Kedungwungu', 564);
insert into cities (name, country_id) values ('Santiago de Baney', 439);
insert into cities (name, country_id) values ('Trai Ngau', 236);
insert into cities (name, country_id) values ('Simpang', 260);
insert into cities (name, country_id) values ('Effium', 580);
insert into cities (name, country_id) values ('Weiting', 364);
insert into cities (name, country_id) values ('Gunungangka', 146);
insert into cities (name, country_id) values ('Sinarbakti', 704);
insert into cities (name, country_id) values ('Pargas', 39);
insert into cities (name, country_id) values ('Sangpi', 651);
insert into cities (name, country_id) values ('Jimsar', 983);
insert into cities (name, country_id) values ('Jandir', 682);
insert into cities (name, country_id) values ('Wuyo', 624);
insert into cities (name, country_id) values ('Helsingborg', 959);
insert into cities (name, country_id) values ('Kuršumlija', 624);
insert into cities (name, country_id) values ('Candelaria', 877);
insert into cities (name, country_id) values ('Bali', 192);
insert into cities (name, country_id) values ('Longar', 94);
insert into cities (name, country_id) values ('Sinacaban', 326);
insert into cities (name, country_id) values ('Ijūin', 383);
insert into cities (name, country_id) values ('Jijiazhuang', 119);
insert into cities (name, country_id) values ('San Isidro', 694);
insert into cities (name, country_id) values ('Vitebsk', 661);
insert into cities (name, country_id) values ('Emmen', 809);
insert into cities (name, country_id) values ('Jiaxian Chengguanzhen', 264);
insert into cities (name, country_id) values ('Tenjolaya', 285);
insert into cities (name, country_id) values ('Uppsala', 478);
insert into cities (name, country_id) values ('Gnieżdżewo', 867);
insert into cities (name, country_id) values ('San Juan', 694);
insert into cities (name, country_id) values ('Antimácheia', 286);
insert into cities (name, country_id) values ('Montague', 247);
insert into cities (name, country_id) values ('Xing’an', 367);
insert into cities (name, country_id) values ('Kävlinge', 245);
insert into cities (name, country_id) values ('Conchucos', 677);
insert into cities (name, country_id) values ('Hekou', 995);
insert into cities (name, country_id) values ('Cieurih Satu', 608);
insert into cities (name, country_id) values ('Birendranagar', 859);
insert into cities (name, country_id) values ('Zvishavane', 807);
insert into cities (name, country_id) values ('Vila Chã', 168);
insert into cities (name, country_id) values ('Verkhniy Rohachyk', 205);
insert into cities (name, country_id) values ('Guaçuí', 794);
insert into cities (name, country_id) values ('Kansas City', 137);
insert into cities (name, country_id) values ('Tajerouine', 906);
insert into cities (name, country_id) values ('Nowshera', 51);
insert into cities (name, country_id) values ('Chaplygin', 829);
insert into cities (name, country_id) values ('San Felipe', 941);
insert into cities (name, country_id) values ('Boroko', 321);
insert into cities (name, country_id) values ('Hongsipu', 409);
insert into cities (name, country_id) values ('Vyshneye Dolgoye', 872);
insert into cities (name, country_id) values ('Pidvolochys’k', 236);
insert into cities (name, country_id) values ('Stenungsund', 447);
insert into cities (name, country_id) values ('Piteå', 686);
insert into cities (name, country_id) values ('El Calafate', 229);
insert into cities (name, country_id) values ('Žandov', 977);
insert into cities (name, country_id) values ('Jayanca', 491);
insert into cities (name, country_id) values ('Dazhongzhuang', 70);
insert into cities (name, country_id) values ('Rijeka', 228);
insert into cities (name, country_id) values ('Kireyevsk', 716);
insert into cities (name, country_id) values ('Baota', 309);
insert into cities (name, country_id) values ('Santa Catalina - Dique Lujan', 122);
insert into cities (name, country_id) values ('Vannes', 230);
insert into cities (name, country_id) values ('Chrząstowice', 229);
insert into cities (name, country_id) values ('Narach', 499);
insert into cities (name, country_id) values ('Pervomaysk', 728);
insert into cities (name, country_id) values ('Wagar', 584);
insert into cities (name, country_id) values ('Neftegorsk', 123);
insert into cities (name, country_id) values ('Tambong', 515);
insert into cities (name, country_id) values ('Planken', 93);
insert into cities (name, country_id) values ('Koygorodok', 547);
insert into cities (name, country_id) values ('Kalávryta', 263);
insert into cities (name, country_id) values ('São Mamede de Infesta', 766);
insert into cities (name, country_id) values ('Kalmunai', 653);
insert into cities (name, country_id) values ('Zadní Mostek', 97);
insert into cities (name, country_id) values ('Stoczek Łukowski', 836);
insert into cities (name, country_id) values ('Kozhevnikovo', 356);
insert into cities (name, country_id) values ('Faleula', 255);
insert into cities (name, country_id) values ('Al Başrah', 237);
insert into cities (name, country_id) values ('San Martin', 413);
insert into cities (name, country_id) values ('Hrotovice', 743);
insert into cities (name, country_id) values ('Libertad', 490);
insert into cities (name, country_id) values ('Tumauini', 722);
insert into cities (name, country_id) values ('Callanca', 697);
insert into cities (name, country_id) values ('Massy', 369);
insert into cities (name, country_id) values ('Zhemtala', 80);
insert into cities (name, country_id) values ('Velikiye Borki', 751);
insert into cities (name, country_id) values ('Dobrich', 853);
insert into cities (name, country_id) values ('Kraaifontein', 667);
insert into cities (name, country_id) values ('Paris 14', 238);
insert into cities (name, country_id) values ('Kyrylivka', 569);
insert into cities (name, country_id) values ('Lumil', 346);
insert into cities (name, country_id) values ('Paoay', 544);
insert into cities (name, country_id) values ('Touba', 779);
insert into cities (name, country_id) values ('Ust’-Isha', 747);
insert into cities (name, country_id) values ('Qingchuan', 442);
insert into cities (name, country_id) values ('Tha Bo', 84);
insert into cities (name, country_id) values ('Qorovulbozor Shahri', 409);
insert into cities (name, country_id) values ('Wādī Raḩḩāl', 526);
insert into cities (name, country_id) values ('San José', 277);
insert into cities (name, country_id) values ('Cầu Gồ', 818);
insert into cities (name, country_id) values ('Manhan', 574);
insert into cities (name, country_id) values ('Loma Bonita', 305);
insert into cities (name, country_id) values ('Kuczbork-Osada', 810);
insert into cities (name, country_id) values ('San Jose', 758);
insert into cities (name, country_id) values ('Adelaide Mail Centre', 904);
insert into cities (name, country_id) values ('Paupanda Bawah', 420);
insert into cities (name, country_id) values ('Xiaocun', 836);
insert into cities (name, country_id) values ('Bom Despacho', 745);
insert into cities (name, country_id) values ('Le Cannet', 803);
insert into cities (name, country_id) values ('Káto Asítai', 84);
insert into cities (name, country_id) values ('Nuwaybi‘a', 856);
insert into cities (name, country_id) values ('Huaqiao', 780);
insert into cities (name, country_id) values ('Coloncito', 49);
insert into cities (name, country_id) values ('Qinglin', 691);
insert into cities (name, country_id) values ('Biggar', 354);
insert into cities (name, country_id) values ('Wellington', 566);
insert into cities (name, country_id) values ('Bābolsar', 739);
insert into cities (name, country_id) values ('Hushan', 330);
insert into cities (name, country_id) values ('Charlemagne', 702);
insert into cities (name, country_id) values ('Wuma', 744);
insert into cities (name, country_id) values ('Zhijiang', 693);
insert into cities (name, country_id) values ('Cervantes', 365);
insert into cities (name, country_id) values ('Thị Trấn Tam Sơn', 36);
insert into cities (name, country_id) values ('Bozhou', 297);
insert into cities (name, country_id) values ('Laholm', 976);
insert into cities (name, country_id) values ('Huqiu', 84);
insert into cities (name, country_id) values ('Cincinnati', 328);
insert into cities (name, country_id) values ('Naples', 800);
insert into cities (name, country_id) values ('Bajo Pichanaqui', 723);
insert into cities (name, country_id) values ('Guagua', 586);
insert into cities (name, country_id) values ('Butigui', 582);
insert into cities (name, country_id) values ('Orzech', 305);
insert into cities (name, country_id) values ('Jistebnice', 220);
insert into cities (name, country_id) values ('Mandaon', 211);
insert into cities (name, country_id) values ('Marolambo', 549);
insert into cities (name, country_id) values ('Lalauigan', 308);
insert into cities (name, country_id) values ('Kuttu', 290);
insert into cities (name, country_id) values ('Lins', 573);
insert into cities (name, country_id) values ('Rušanj', 922);
insert into cities (name, country_id) values ('Sueyoshichō-ninokata', 816);
insert into cities (name, country_id) values ('Boskovice', 184);
insert into cities (name, country_id) values ('Orós', 36);
insert into cities (name, country_id) values ('Cimaragas', 712);
insert into cities (name, country_id) values ('‘Izbat al Burj', 169);
insert into cities (name, country_id) values ('Los Angeles', 513);
insert into cities (name, country_id) values ('Laxou', 202);
insert into cities (name, country_id) values ('Áno Kalentíni', 139);
insert into cities (name, country_id) values ('Osório', 767);
insert into cities (name, country_id) values ('Jāwā', 92);
insert into cities (name, country_id) values ('Huangjin', 963);
insert into cities (name, country_id) values ('San Teodoro', 262);
insert into cities (name, country_id) values ('Guiset East', 487);
insert into cities (name, country_id) values ('Libertador General San Martín', 149);
insert into cities (name, country_id) values ('Nanggela', 830);
insert into cities (name, country_id) values ('Wadung', 769);
insert into cities (name, country_id) values ('Dunmanway', 833);
insert into cities (name, country_id) values ('Malapaubhara', 222);
insert into cities (name, country_id) values ('Bularit', 458);
insert into cities (name, country_id) values ('Kokop', 440);
insert into cities (name, country_id) values ('Krajan Menggare', 122);
insert into cities (name, country_id) values ('Karuri', 965);
insert into cities (name, country_id) values ('Charikar', 714);
insert into cities (name, country_id) values ('Al Badārī', 534);
insert into cities (name, country_id) values ('Jiaogong', 145);
insert into cities (name, country_id) values ('Udi', 1000);
insert into cities (name, country_id) values ('Ganghwa-gun', 655);
insert into cities (name, country_id) values ('Ouro Branco', 493);
insert into cities (name, country_id) values ('Xirikxiy', 454);
insert into cities (name, country_id) values ('Springfield', 682);
insert into cities (name, country_id) values ('Annino', 207);
insert into cities (name, country_id) values ('Lesnoy', 733);
insert into cities (name, country_id) values ('Alicia', 337);
insert into cities (name, country_id) values ('El Calvario', 674);
insert into cities (name, country_id) values ('Mancha Khiri', 841);
insert into cities (name, country_id) values ('Santana', 312);
insert into cities (name, country_id) values ('Xiaojinkou', 523);
insert into cities (name, country_id) values ('Taldyqorghan', 522);
insert into cities (name, country_id) values ('Santa Valha', 233);
insert into cities (name, country_id) values ('Kitakata', 359);
insert into cities (name, country_id) values ('Mogoditshane', 440);
insert into cities (name, country_id) values ('Mabilang', 145);
insert into cities (name, country_id) values ('Leuwibuleud', 802);
insert into cities (name, country_id) values ('Iqaluit', 561);
insert into cities (name, country_id) values ('Tandou', 129);
insert into cities (name, country_id) values ('Charlestown', 306);
insert into cities (name, country_id) values ('Baojia', 345);
insert into cities (name, country_id) values ('Log', 543);
insert into cities (name, country_id) values ('Maracaju', 325);
insert into cities (name, country_id) values ('Chicago', 785);
insert into cities (name, country_id) values ('Buan', 822);
insert into cities (name, country_id) values ('Colomiers', 630);
insert into cities (name, country_id) values ('Krajan Tengah', 857);
insert into cities (name, country_id) values ('Qinglong', 442);
insert into cities (name, country_id) values ('Lajkovac', 477);
insert into cities (name, country_id) values ('Maharagama', 884);
insert into cities (name, country_id) values ('Potelych', 361);
insert into cities (name, country_id) values ('Hanjiaji', 647);
insert into cities (name, country_id) values ('La Foa', 230);
insert into cities (name, country_id) values ('Rucava', 710);
insert into cities (name, country_id) values ('Port Louis', 83);
insert into cities (name, country_id) values ('Kota Kinabalu', 204);
insert into cities (name, country_id) values ('Watergrasshill', 690);
insert into cities (name, country_id) values ('San Jose', 44);
insert into cities (name, country_id) values ('Kotel’va', 741);
insert into cities (name, country_id) values ('Dazhou', 738);
insert into cities (name, country_id) values ('Santiago', 890);
insert into cities (name, country_id) values ('Huangsha', 231);
insert into cities (name, country_id) values ('Dayou', 426);
insert into cities (name, country_id) values ('Banjar Dauhpura', 66);
insert into cities (name, country_id) values ('Klapagading', 291);
insert into cities (name, country_id) values ('Koesan', 462);
insert into cities (name, country_id) values ('Linglong', 599);
insert into cities (name, country_id) values ('Fengyang', 1000);
insert into cities (name, country_id) values ('Fujikawaguchiko', 902);
insert into cities (name, country_id) values ('Debre Zeyit', 334);
insert into cities (name, country_id) values ('Saint Louis', 272);
insert into cities (name, country_id) values ('Kalepasan', 641);
insert into cities (name, country_id) values ('Kharagauli', 829);
insert into cities (name, country_id) values ('Bayt ‘Awwā', 844);
insert into cities (name, country_id) values ('Umeå', 540);
insert into cities (name, country_id) values ('Simimbaan', 771);
insert into cities (name, country_id) values ('Lhokkruet', 1);
insert into cities (name, country_id) values ('Kanggye-si', 608);
insert into cities (name, country_id) values ('Villa Carlos Paz', 107);
insert into cities (name, country_id) values ('Kinzan', 402);
insert into cities (name, country_id) values ('Rodionovo-Nesvetayskaya', 79);
insert into cities (name, country_id) values ('Paizhou', 320);
insert into cities (name, country_id) values ('Gambalidio', 700);
insert into cities (name, country_id) values ('Pandakan', 467);
insert into cities (name, country_id) values ('Ganjiachang', 47);
insert into cities (name, country_id) values ('Montpellier', 887);
insert into cities (name, country_id) values ('Shetan', 128);
insert into cities (name, country_id) values ('Pangal Sur', 241);
insert into cities (name, country_id) values ('Sofifi', 487);
insert into cities (name, country_id) values ('Pushkino', 635);
insert into cities (name, country_id) values ('Santa Fe de la Vera Cruz', 922);
insert into cities (name, country_id) values ('Agusan', 451);
insert into cities (name, country_id) values ('Lunenburg', 613);
insert into cities (name, country_id) values ('Luotuo', 439);
insert into cities (name, country_id) values ('Cruz das Almas', 702);
insert into cities (name, country_id) values ('Ravne', 416);
insert into cities (name, country_id) values ('Nice', 65);
insert into cities (name, country_id) values ('Bemposta', 380);
insert into cities (name, country_id) values ('Radostowice', 936);
insert into cities (name, country_id) values ('Meipu', 758);
insert into cities (name, country_id) values ('Sukarame', 834);
insert into cities (name, country_id) values ('Belén de Escobar', 881);
insert into cities (name, country_id) values ('Khe Tre', 112);
insert into cities (name, country_id) values ('Dallas', 367);
insert into cities (name, country_id) values ('Siva', 858);
insert into cities (name, country_id) values ('Munjul', 821);
insert into cities (name, country_id) values ('Arnaía', 459);
insert into cities (name, country_id) values ('Cifuentes', 426);
insert into cities (name, country_id) values ('Obudu', 222);
insert into cities (name, country_id) values ('Wien', 895);
insert into cities (name, country_id) values ('Oehala', 517);
insert into cities (name, country_id) values ('Guandian', 531);
insert into cities (name, country_id) values ('Limoges', 601);
insert into cities (name, country_id) values ('Zhaozhen', 947);
insert into cities (name, country_id) values ('Yuanyang Zhen', 70);
insert into cities (name, country_id) values ('Krajan Ngerdani', 92);
insert into cities (name, country_id) values ('Lang Suan', 975);
insert into cities (name, country_id) values ('Moyuan', 543);
insert into cities (name, country_id) values ('Burträsk', 739);
insert into cities (name, country_id) values ('Toyós', 86);
insert into cities (name, country_id) values ('Thị Trấn Tà Lùng', 61);
insert into cities (name, country_id) values ('Ambarakaraka', 66);
insert into cities (name, country_id) values ('Darband', 671);
insert into cities (name, country_id) values ('Fond du Sac', 53);
insert into cities (name, country_id) values ('Irkliyevskaya', 756);
insert into cities (name, country_id) values ('Kibonsod', 780);
insert into cities (name, country_id) values ('Bcharré', 313);
insert into cities (name, country_id) values ('Matahuasi', 495);
insert into cities (name, country_id) values ('Mirošov', 837);
insert into cities (name, country_id) values ('Kašperské Hory', 575);
insert into cities (name, country_id) values ('Shidong', 776);
insert into cities (name, country_id) values ('Tanjay', 953);
insert into cities (name, country_id) values ('Daxing', 355);
insert into cities (name, country_id) values ('Borūjerd', 943);
insert into cities (name, country_id) values ('London', 577);
insert into cities (name, country_id) values ('Zhulan', 519);
insert into cities (name, country_id) values ('São João', 525);
insert into cities (name, country_id) values ('Huinca Renancó', 9);
insert into cities (name, country_id) values ('Sumberbatas', 843);
insert into cities (name, country_id) values ('Telêmaco Borba', 595);
insert into cities (name, country_id) values ('Gali', 1000);
insert into cities (name, country_id) values ('Rennes', 530);
insert into cities (name, country_id) values ('Klisura', 783);
insert into cities (name, country_id) values ('Kapunduk', 432);
insert into cities (name, country_id) values ('Suncheon', 769);
insert into cities (name, country_id) values ('Caikouji', 78);
insert into cities (name, country_id) values ('Jaleswar', 920);
insert into cities (name, country_id) values ('Tuka', 223);
insert into cities (name, country_id) values ('Pimbalayan', 774);
insert into cities (name, country_id) values ('Ostuncalco', 67);
insert into cities (name, country_id) values ('Villa Dolores', 423);
insert into cities (name, country_id) values ('Kukurečani', 49);
insert into cities (name, country_id) values ('Shelabolikha', 13);
insert into cities (name, country_id) values ('Sarandi', 934);
insert into cities (name, country_id) values ('Gareba', 435);
insert into cities (name, country_id) values ('Chalaco', 460);
insert into cities (name, country_id) values ('Port-de-Paix', 674);
insert into cities (name, country_id) values ('Mandaguari', 400);
insert into cities (name, country_id) values ('Kovači', 908);
insert into cities (name, country_id) values ('Cuijiaqiao', 977);
insert into cities (name, country_id) values ('Lombog', 72);
insert into cities (name, country_id) values ('Chatian', 35);
insert into cities (name, country_id) values ('Tange Zhen', 60);
insert into cities (name, country_id) values ('Mukařov', 750);
insert into cities (name, country_id) values ('Veyno', 703);
insert into cities (name, country_id) values ('Gaojia', 727);
insert into cities (name, country_id) values ('Cáceres', 106);
insert into cities (name, country_id) values ('Shawnee Mission', 846);
insert into cities (name, country_id) values ('Libušín', 689);
insert into cities (name, country_id) values ('Ziyang Chengguanzhen', 276);
insert into cities (name, country_id) values ('Sungai Raya', 601);
insert into cities (name, country_id) values ('Beima', 908);
insert into cities (name, country_id) values ('Mikumi', 856);
insert into cities (name, country_id) values ('Usol’ye', 267);
insert into cities (name, country_id) values ('Velille', 480);
insert into cities (name, country_id) values ('Tiepu', 303);
insert into cities (name, country_id) values ('Beira', 9);
insert into cities (name, country_id) values ('Thai Charoen', 675);
insert into cities (name, country_id) values ('P’asanauri', 837);
insert into cities (name, country_id) values ('Markaz Bilād aţ Ţa‘ām', 303);
insert into cities (name, country_id) values ('Shapa', 464);
insert into cities (name, country_id) values ('Čačinci', 39);
insert into cities (name, country_id) values ('Kharp', 970);
insert into cities (name, country_id) values ('Jingzhou', 397);
insert into cities (name, country_id) values ('Kuching', 332);
insert into cities (name, country_id) values ('Banjar Bali', 262);
insert into cities (name, country_id) values ('Betzdorf', 136);
insert into cities (name, country_id) values ('Växjö', 78);
insert into cities (name, country_id) values ('Guanay', 819);
insert into cities (name, country_id) values ('Velká Bíteš', 751);
insert into cities (name, country_id) values ('Xinzhai', 151);
insert into cities (name, country_id) values ('Cumanayagua', 968);
insert into cities (name, country_id) values ('Kotadukuh', 551);
insert into cities (name, country_id) values ('Netolice', 98);
insert into cities (name, country_id) values ('Pérama', 953);
insert into cities (name, country_id) values ('Amiens', 715);
insert into cities (name, country_id) values ('Dawu', 12);
insert into cities (name, country_id) values ('Leon Postigo', 1000);
insert into cities (name, country_id) values ('Longping', 155);
insert into cities (name, country_id) values ('Palaihari', 416);
insert into cities (name, country_id) values ('Fort Worth', 765);
insert into cities (name, country_id) values ('Maogang', 663);
insert into cities (name, country_id) values ('Maykopskoye', 270);
insert into cities (name, country_id) values ('Sumaré', 594);
insert into cities (name, country_id) values ('Shangani', 686);
insert into cities (name, country_id) values ('Kutamandarakan', 364);
insert into cities (name, country_id) values ('Songkeng', 837);
insert into cities (name, country_id) values ('Aimin', 520);
insert into cities (name, country_id) values ('São Mateus do Sul', 518);
insert into cities (name, country_id) values ('Laguna de Perlas', 711);
insert into cities (name, country_id) values ('Erqu', 615);
insert into cities (name, country_id) values ('Hongxing', 429);
insert into cities (name, country_id) values ('Dingqing', 705);
insert into cities (name, country_id) values ('Owczarnia', 618);
insert into cities (name, country_id) values ('Traganón', 64);
insert into cities (name, country_id) values ('Sestroretsk', 334);
insert into cities (name, country_id) values ('Phan Thong', 680);
insert into cities (name, country_id) values ('Ust-Maya', 831);
insert into cities (name, country_id) values ('Shushenskoye', 483);
insert into cities (name, country_id) values ('Al Mālikīyah', 551);
insert into cities (name, country_id) values ('Shiree', 936);
insert into cities (name, country_id) values ('Sang-e Chārak', 926);
insert into cities (name, country_id) values ('Valparaíso', 925);
insert into cities (name, country_id) values ('Hanban', 300);
insert into cities (name, country_id) values ('Hörby', 727);
insert into cities (name, country_id) values ('Qinling Jieban', 118);
insert into cities (name, country_id) values ('Fukuroi', 457);
insert into cities (name, country_id) values ('Xom Tan Long', 411);
insert into cities (name, country_id) values ('Zátor', 291);
insert into cities (name, country_id) values ('Woodstock', 284);
insert into cities (name, country_id) values ('Novi Zagreb', 973);
insert into cities (name, country_id) values ('Tupaciguara', 277);
insert into cities (name, country_id) values ('Kalwaria Zebrzydowska', 63);
insert into cities (name, country_id) values ('Kalipucang', 133);
insert into cities (name, country_id) values ('Lidzbark', 432);
insert into cities (name, country_id) values ('Trai Ngau', 624);
insert into cities (name, country_id) values ('Poitiers', 525);
insert into cities (name, country_id) values ('Chenggang', 900);
insert into cities (name, country_id) values ('Franco da Rocha', 582);
insert into cities (name, country_id) values ('Xinyuan', 709);
insert into cities (name, country_id) values ('Bagusan', 467);
insert into cities (name, country_id) values ('Hakodate', 705);
insert into cities (name, country_id) values ('Tangkilsari', 585);
insert into cities (name, country_id) values ('Castres', 212);
insert into cities (name, country_id) values ('Łopuszno', 681);
insert into cities (name, country_id) values ('Linköping', 721);
insert into cities (name, country_id) values ('Loma Bonita', 545);
insert into cities (name, country_id) values ('Tarsouat', 502);
insert into cities (name, country_id) values ('Ete', 401);
insert into cities (name, country_id) values ('Huanren', 897);
insert into cities (name, country_id) values ('Pul-e Sangī', 444);
insert into cities (name, country_id) values ('Parry Sound', 800);
insert into cities (name, country_id) values ('Petrovskiy', 932);
insert into cities (name, country_id) values ('Svojat', 94);
insert into cities (name, country_id) values ('Ialibu', 410);
insert into cities (name, country_id) values ('Skuhrov nad Bělou', 67);
insert into cities (name, country_id) values ('Dzerzhinskiy', 514);
insert into cities (name, country_id) values ('Ciroyom', 416);
insert into cities (name, country_id) values ('Bohdalov', 802);
insert into cities (name, country_id) values ('New Haven', 445);
insert into cities (name, country_id) values ('Zarzis', 617);
insert into cities (name, country_id) values ('Benito Juarez', 971);
insert into cities (name, country_id) values ('Zaandam', 245);
insert into cities (name, country_id) values ('Rungis', 28);
insert into cities (name, country_id) values ('Tuanzhou', 506);
insert into cities (name, country_id) values ('Concepción de Ataco', 873);
insert into cities (name, country_id) values ('Waihi', 430);
insert into cities (name, country_id) values ('Shanxi', 769);
insert into cities (name, country_id) values ('Novorozhdestvenskaya', 166);
insert into cities (name, country_id) values ('Bancar', 433);
insert into cities (name, country_id) values ('Boawae', 55);
insert into cities (name, country_id) values ('Toulon', 829);
insert into cities (name, country_id) values ('Riđica', 883);
insert into cities (name, country_id) values ('Dananyu', 270);
insert into cities (name, country_id) values ('Batukuta', 2);
insert into cities (name, country_id) values ('Xaysetha', 529);
insert into cities (name, country_id) values ('Yupiltepeque', 371);
insert into cities (name, country_id) values ('Baisha', 152);
insert into cities (name, country_id) values ('Mizoch', 343);
insert into cities (name, country_id) values ('Pulaupanggung', 504);
insert into cities (name, country_id) values ('Lefkímmi', 262);
insert into cities (name, country_id) values ('Litvínov', 991);
insert into cities (name, country_id) values ('Ospina', 961);
insert into cities (name, country_id) values ('La Soledad', 179);
insert into cities (name, country_id) values ('Noyal-sur-Vilaine', 711);
insert into cities (name, country_id) values ('Amiens', 769);
insert into cities (name, country_id) values ('Agrínio', 305);
insert into cities (name, country_id) values ('Osa', 257);
insert into cities (name, country_id) values ('Šmartno pri Litiji', 432);
insert into cities (name, country_id) values ('Paris 20', 875);
insert into cities (name, country_id) values ('Dayou', 936);
insert into cities (name, country_id) values ('Ōmachi', 280);
insert into cities (name, country_id) values ('Vřesina', 910);
insert into cities (name, country_id) values ('Tatarsk', 307);
insert into cities (name, country_id) values ('Hejiayan', 586);
insert into cities (name, country_id) values ('Muaratiga', 507);
insert into cities (name, country_id) values ('Shuiying', 117);
insert into cities (name, country_id) values ('Muff', 893);
insert into cities (name, country_id) values ('Staré Křečany', 129);
insert into cities (name, country_id) values ('Mudanjiang', 487);
insert into cities (name, country_id) values ('Baraya', 718);
insert into cities (name, country_id) values ('Santulhão', 709);
insert into cities (name, country_id) values ('Viekšniai', 737);
insert into cities (name, country_id) values ('Banī Suhaylā', 299);
insert into cities (name, country_id) values ('Maddela', 3);
insert into cities (name, country_id) values ('Semarang', 176);
insert into cities (name, country_id) values ('Hepingjie', 825);
insert into cities (name, country_id) values ('Dadus', 403);
insert into cities (name, country_id) values ('Deranitan', 314);
insert into cities (name, country_id) values ('Xushan', 585);
insert into cities (name, country_id) values ('Daming', 376);
insert into cities (name, country_id) values ('Des Moines', 980);
insert into cities (name, country_id) values ('Reshetikha', 619);
insert into cities (name, country_id) values ('Kthella e Epërme', 882);
insert into cities (name, country_id) values ('Sadek', 189);
insert into cities (name, country_id) values ('Quebradas', 439);
insert into cities (name, country_id) values ('Huxu', 605);
insert into cities (name, country_id) values ('Pinayagan Norte', 59);
insert into cities (name, country_id) values ('Lupak', 420);
insert into cities (name, country_id) values ('Luoyuan', 828);
insert into cities (name, country_id) values ('Daduchuan', 24);
insert into cities (name, country_id) values ('Den Chai', 735);
insert into cities (name, country_id) values ('Khudāydād Khēl', 3);
insert into cities (name, country_id) values ('Umeå', 524);
insert into cities (name, country_id) values ('Blumenau', 551);
insert into cities (name, country_id) values ('Kuala Belait', 190);
insert into cities (name, country_id) values ('Duncan', 382);
insert into cities (name, country_id) values ('Puntaru', 303);
insert into cities (name, country_id) values ('Beau Vallon', 714);
insert into cities (name, country_id) values ('Trzebnica', 756);
insert into cities (name, country_id) values ('Banaba', 38);
insert into cities (name, country_id) values ('Nagato', 761);
insert into cities (name, country_id) values ('Toroy', 671);
insert into cities (name, country_id) values ('Slunj', 838);
insert into cities (name, country_id) values ('Liuzhuang', 183);
insert into cities (name, country_id) values ('Talodi', 730);
insert into cities (name, country_id) values ('Taling', 135);
insert into cities (name, country_id) values ('Presnenskiy', 361);
insert into cities (name, country_id) values ('Barão de São Miguel', 898);
insert into cities (name, country_id) values ('Shijiao', 221);
insert into cities (name, country_id) values ('Tiandeng', 170);
insert into cities (name, country_id) values ('Wadung', 155);
insert into cities (name, country_id) values ('Selebi-Phikwe', 944);
insert into cities (name, country_id) values ('Antanifotsy', 226);
insert into cities (name, country_id) values ('Allanridge', 80);
insert into cities (name, country_id) values ('Bakung Utara', 14);
insert into cities (name, country_id) values ('Bromma', 390);
insert into cities (name, country_id) values ('Florida', 345);
insert into cities (name, country_id) values ('Nay Pyi Taw', 163);
insert into cities (name, country_id) values ('Idanre', 623);
insert into cities (name, country_id) values ('Salavan', 319);
insert into cities (name, country_id) values ('Hluboká nad Vltavou', 952);
insert into cities (name, country_id) values ('Beigang', 534);
insert into cities (name, country_id) values ('Garko', 892);
insert into cities (name, country_id) values ('Tuymazy', 342);
insert into cities (name, country_id) values ('Göteborg', 724);
insert into cities (name, country_id) values ('Huayuanli', 546);
insert into cities (name, country_id) values ('Chong’ansi', 729);
insert into cities (name, country_id) values ('Bandjoun', 292);
insert into cities (name, country_id) values ('Wolometang', 214);
insert into cities (name, country_id) values ('Zhangxiong', 316);
insert into cities (name, country_id) values ('Bendo', 457);
insert into cities (name, country_id) values ('Vallenar', 271);
insert into cities (name, country_id) values ('Guanagazapa', 491);
insert into cities (name, country_id) values ('Karuri', 904);
insert into cities (name, country_id) values ('Asia', 864);
insert into cities (name, country_id) values ('Huangshapu', 161);
insert into cities (name, country_id) values ('Santol', 778);
insert into cities (name, country_id) values ('Mendeleyevsk', 116);
insert into cities (name, country_id) values ('Puerto Iguazú', 39);
insert into cities (name, country_id) values ('Oltinko’l', 471);
insert into cities (name, country_id) values ('Barda', 2);
insert into cities (name, country_id) values ('San Agustin', 913);
insert into cities (name, country_id) values ('Shuangqiao', 706);
insert into cities (name, country_id) values ('Hollywood', 411);
insert into cities (name, country_id) values ('Simpang', 505);
insert into cities (name, country_id) values ('Khlong Luang', 480);
insert into cities (name, country_id) values ('Mineralni Bani', 203);
insert into cities (name, country_id) values ('Taiqing', 230);
insert into cities (name, country_id) values ('Allentown', 450);
insert into cities (name, country_id) values ('Cimara', 436);
insert into cities (name, country_id) values ('Jiangya', 259);
insert into cities (name, country_id) values ('Guadalupe', 117);
insert into cities (name, country_id) values ('Atok', 480);
insert into cities (name, country_id) values ('Bené Beraq', 879);
insert into cities (name, country_id) values ('Penitik', 53);
insert into cities (name, country_id) values ('Xiangtan', 696);
insert into cities (name, country_id) values ('Pitogo', 81);
insert into cities (name, country_id) values ('Madoi', 871);
insert into cities (name, country_id) values ('Dolice', 953);
insert into cities (name, country_id) values ('Sanxiang', 371);
insert into cities (name, country_id) values ('Werang', 200);
insert into cities (name, country_id) values ('Ar Rawnah', 887);
insert into cities (name, country_id) values ('Amapala', 710);
insert into cities (name, country_id) values ('Jingkou', 643);
insert into cities (name, country_id) values ('Quimper', 843);
insert into cities (name, country_id) values ('Floda', 325);
insert into cities (name, country_id) values ('Magangué', 458);
insert into cities (name, country_id) values ('Nueva Requena', 311);
insert into cities (name, country_id) values ('Gewanē', 477);
insert into cities (name, country_id) values ('Gangnan', 447);
insert into cities (name, country_id) values ('Baxiangshan', 718);
insert into cities (name, country_id) values ('Sewon', 281);
insert into cities (name, country_id) values ('Libu', 812);
insert into cities (name, country_id) values ('Nanzamu', 944);
insert into cities (name, country_id) values ('Yongning', 55);
insert into cities (name, country_id) values ('Atyrá', 494);
insert into cities (name, country_id) values ('Foros de Salvaterra', 776);
insert into cities (name, country_id) values ('Toulouse', 782);
insert into cities (name, country_id) values ('Oslo', 923);
insert into cities (name, country_id) values ('Ituiutaba', 660);
insert into cities (name, country_id) values ('Stockholm', 507);
insert into cities (name, country_id) values ('Vukovije Donje', 456);
insert into cities (name, country_id) values ('Stizhkivs’ke', 771);
insert into cities (name, country_id) values ('Changpo', 842);
insert into cities (name, country_id) values ('Haradok', 413);
insert into cities (name, country_id) values ('Xishaping', 334);
insert into cities (name, country_id) values ('Balzar', 937);
insert into cities (name, country_id) values ('Donglai', 688);
insert into cities (name, country_id) values ('Gunungjulang', 415);
insert into cities (name, country_id) values ('Hongqi', 173);
insert into cities (name, country_id) values ('Água Preta', 284);
insert into cities (name, country_id) values ('Sarandi', 112);
insert into cities (name, country_id) values ('Padangtiji', 895);
insert into cities (name, country_id) values ('Huaping', 262);
insert into cities (name, country_id) values ('Dungkek Laok', 437);
insert into cities (name, country_id) values ('Indianapolis', 414);
insert into cities (name, country_id) values ('Dmanisi', 8);
insert into cities (name, country_id) values ('Phanom Phrai', 157);
insert into cities (name, country_id) values ('Orléans', 132);
insert into cities (name, country_id) values ('Ivyanyets', 790);
insert into cities (name, country_id) values ('Abhar', 706);
insert into cities (name, country_id) values ('la Massana', 438);
insert into cities (name, country_id) values ('Talagasari', 984);
insert into cities (name, country_id) values ('Horní Suchá', 600);
insert into cities (name, country_id) values ('Suna', 484);
insert into cities (name, country_id) values ('Redcliff', 547);
insert into cities (name, country_id) values ('Dama', 952);
insert into cities (name, country_id) values ('San Sebastian', 713);
