package com.edaakyil.generator.password.entity;

import lombok.*;
import lombok.experimental.Accessors;

import java.time.LocalDateTime;

@Getter
@Setter
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class UserInfo {
    @Accessors(prefix = "m_")
    private String m_username;

    @Accessors(prefix = "m_")
    private String m_password;

    @Accessors(prefix = "m_")
    private int m_count;   // The number of passwords created by user

    @Accessors(prefix = "m_")
    private int m_len;  // The length of each password generated by user

    @Accessors(prefix = "m_")
    private LocalDateTime m_registerTime;

    public UserInfo(String username)
    {
        m_username = username;
    }
}
